### ISSUE TITLE
Change button colors of email sign-up and 'copy link'

### ISSUE THREAD

**Issue by natalieworth** [mozilla/advocacy.mozilla.org#517]
The button colors of the donate pop-up are currently red, and the copy link is a subtle grey. 

We need to change these to #03a8a8.

- [ ] Change donate pop-up button to #03a8a8
- [ ] Change 'copy link' to #03a8a8
- [ ] Remove the 'copy link' opacity
- [ ] Add hover state color #007575 to donate and copy link buttons

**Comment by natalieworth** [comment]
Changes:
<img width="370" alt="screen shot 2018-03-06 at 10 57 18 am" src="https://user-images.githubusercontent.com/14876567/37058062-217afc82-213e-11e8-8a3e-63d5f529b80d.png">
<img width="1360" alt="screen shot 2018-03-06 at 10 59 45 am" src="https://user-images.githubusercontent.com/14876567/37058063-21925bc0-213e-11e8-9bd0-3751309e3c3a.png">
